# Generated by Django 5.2.7 on 2026-01-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_comment_created_at_comment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmboxuser',
            name='encrypted_password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='filmboxuser',
            name='session_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
