# Generated by Django 5.2.7 on 2026-01-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_comment_created_at_comment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.FloatField(),
        ),
    ]
